# Generated by Django 4.2.3 on 2023-07-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='price',
            new_name='priceS_per_night',
        ),
    ]
